---
repository: sproogen/resume-theme
favicon: images/favicon.ico
version: 2
name: Sanjoli Omar
title: Software Developer
email: sanjoliofficial01@gmail.com
website: www.github.com/me-sanjoli
darkmode: false
github_username: me-sanjoli
linkedin_username: https://www.linkedin.com/in/profilesanjoli/
about_profile_image: images/WhatsApp Image 2023-11-26 at 11.51.25.jpeg
about_content: >
  Hi, my name's Sanjoli and I'm a Software developer. As a Java Developer, I am passionate about building high-quality software applications that are scalable, reliable, and maintainable. With experience working on various projects, I have developed expertise in Java and related technologies.
  My technical skills include proficiency in Java programming, Spring Framework, Hibernate, and RESTful web services. I also have experience with front-end technologies such as HTML, CSS, and JavaScript, which enable me to develop full-stack applications.
  In my previous roles, I have collaborated with cross-functional teams to develop software solutions that meet business requirements and deliver value to end-users. I am a quick learner and always eager to explore new technologies and tools that can enhance the quality and performance of my code.
  If you're looking for a Java Developer who can deliver high-quality software solutions, please don't hesitate to reach out. I'm always open to discussing new opportunities and challenges.


  I am most skilled in: <mark>Java</mark>, <mark>SQL</mark> and ofcourse <mark>Watching Anime</mark>!
content:
  - title: Skills
    layout: list
    content:
      - layout: left
        sub_title: Languages
        description: >
          Java, SQL, JavaScript, Python, HTML, CSS, XML, Typescript, Arduino,
          C++, and MATLAB.
      - layout: left
        sub_title: Frameworks/Technologies
        description: >
          Git, REST, Java struts, servlets, Jboss, J2EE, Spring boot, Azure,
          SoapUI, JIRA, Bitbucket, and Dbeaver.
      - layout: left
        sub_title: Areas of Interest
        description: |
          Problem Solving, Machine Learning, DSA and Algorithms.
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Sapiens Technologies (1982) India Private Limited, Bangalore
        link: https://sapiens.com/
        sub_title: Java Developer
        caption: January 2022 - Present
        quote: >
          Primarily focus on customization of Sapiens' IDIT product in Property &
          Casualty Insurance domain 
        description: >
          My responsibilities extend to both front-end and back-end
          development, where I've had the opportunity to design and manage
          database schemas and queries using SQL over Oracle database. 

          I have had opportunity to work in creating APIs. Additionally, I've been actively involved in code reviews, debugging, and troubleshooting to ensure the delivery of high-quality solutions. 

          Furthermore, I've had the privilege of mentoring and training junior developers, maintaning their metrics on JIRA and monitoring there performances, contributing to the team's growth and cohesiveness.
      - layout: center
        title: Tata Consultancy Services
        link: https://www.tcs.com/
        sub_title: Software Developer
        caption: July 2019 - January 2022
        quote: >
          Maintenance and enhancement of a Project Portfolio application with Java
          for a major US pharmaceutical firm.
        description: >
          I was responsible for developing and maintaining web application
          using Java. I acquired proficiency in Java programming language, software development lifecycle and agile methodologies

          Also critical testing using automation tools such as selenium webdriver and bug fixing
  - title: A Little More About Me
    layout: text
    content: >
      Alongside my interests in networks and software engineering some of my
      other interests and hobbies are:

      - [Writing blog : link ->](https://witchblackproject.wordpress.com)

      - Gaming

      - Watching crime documentaries

      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)
footer_show_references: true
remote_theme: sproogen/resume-theme
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-seo-tag
